VL-104 [BACKEND] App monitoring
kacpersosnowski/virtual_library pull request #104
Opened 2024-05-27 13:56 UTC by kacpersosnowski

2024-05-28 10:12 UTC, malafier requested changes

2024-05-28 10:12 UTC, malafier commented on docker/docker-compose.yml
> +  grafana:
grafana powinna być w sieci

2024-05-29 11:18 UTC, sebastian-jedrzejewski commented on docker/docker-compose.yml
> +    networks:
Dodaj Prometeusza do sieci frontendowej

2024-06-01 11:12 UTC, malafier approved these changes

2024-06-01 11:44 UTC, merged