VL-56 [BACKEND] Add search for author and genre
kacpersosnowski/virtual_library pull request #51
Opened 2024-02-13 16:22 UTC by malafier

2024-02-16 10:01 UTC, kacpersosnowski requested changes

2024-02-16 10:01 UTC, kacpersosnowski commented on backend/src/main/java/com/skr/virtuallibrary/controllers/AuthorController.java
>  package com.skr.virtuallibrary.controllers;
Nie wszystkie testy przechodzą

2024-02-16 10:13 UTC, kacpersosnowski commented on backend/src/main/java/com/skr/virtuallibrary/services/AuthorService.java
> +    public PagedResponse<AuthorDto> searchAuthors(String name) {
Do tych metod searchAuthors można dodać testy

2024-02-16 10:34 UTC, malafier commented on backend/src/main/java/com/skr/virtuallibrary/controllers/AuthorController.java
> +    @ApiResponse(responseCode = "500")
usunięte

2024-02-16 10:34 UTC, malafier commented on backend/src/main/java/com/skr/virtuallibrary/services/AuthorService.java
> +        }
wyciągnięte

2024-02-16 12:52 UTC, malafier commented on backend/src/main/java/com/skr/virtuallibrary/controllers/AuthorController.java
>  package com.skr.virtuallibrary.controllers;
poprawione

2024-02-22 17:18 UTC, malafier commented on backend/src/main/java/com/skr/virtuallibrary/services/AuthorService.java
> +    public PagedResponse<AuthorDto> searchAuthors(String name) {
dodane

2024-02-22 20:14 UTC, kacpersosnowski approved these changes

2024-02-22 21:29 UTC, merged