VL-83 [BACKEND] User update
kacpersosnowski/virtual_library pull request #75
Opened 2024-03-18 20:05 UTC by kacpersosnowski

2024-03-18 20:46 UTC, sebastian-jedrzejewski commented on backend/src/main/java/com/skr/virtuallibrary/controllers/UserController.java
> +            @Valid @RequestPart("user")UpdateUserRequest request,
Tutaj brakuje spacji
```suggestion
            @Valid @RequestPart("user") UpdateUserRequest request,
```

2024-03-21 00:12 UTC, malafier requested changes

2024-03-21 00:12 UTC, malafier commented on backend/src/main/java/com/skr/virtuallibrary/services/UserService.java
> +        if (request.getProfilePictureId() != null) {
Tu powinna być większa walidacja. Skoro `profilePicture` w Controllerze nie jest obowiązkowe, to ktoś może wysłać requesta z błędnym id zdjęcia profilowego. Serwis powinien wiedzieć czy zdjęcie zostało nadesłane z Controllera lub sprawdzić, czy takowe już istnieje.

2024-03-22 19:50 UTC, sebastian-jedrzejewski approved these changes

2024-03-22 19:52 UTC, merged