VL-107 [BACKEND] Search users
kacpersosnowski/virtual_library pull request #99
Opened 2024-05-10 16:59 UTC by kacpersosnowski

2024-05-11 20:50 UTC, malafier reviewed
Czy użytkownik nie powinien mieć możliwości ustawienia konta na prywatne, żeby nie można wyszukać?

2024-05-14 19:06 UTC, kacpersosnowski commented
> Czy użytkownik nie powinien mieć możliwości ustawienia konta na prywatne, żeby nie można wyszukać?

poprawione

2024-05-17 09:13 UTC, malafier requested changes
Dwie dodatkowe sprawy:
1. Chyba jest problem z mapperem: przy odpowiedzi pole użytkownika zawsze ma `publicAccount: flase` (a powinno być true, filtrowanie w bazie danych jest dobrze).
2. Czy użytkownik wyszukujący innego użytkownika powinien móc widzieć jego maila (jest przesyłany w odpowiedzi)?

2024-05-18 16:22 UTC, kacpersosnowski commented on backend/src/main/java/com/skr/virtuallibrary/auth/AuthenticationService.java
> +                .publicAccount(true)
> jw. `publicAccount` należy dodać też do `UnregisteredUser`

poprawione

2024-05-18 16:40 UTC, malafier approved these changes

2024-05-18 16:40 UTC, merged